### ISSUE TITLE
Failed to resolve directive: ripple

### ISSUE THREAD

**Issue by sandroden** [DoritoBandito/vuetify-upload-button#14]
I'm using rel 1.2.2 that should hae resolved "ripple bug" but I have this warning:

```
[Vue warn]: Failed to resolve directive: ripple
(found in <UploadBtn>)
```
and I don't have ripple prop, I call upload-btn as follows:

```html
<upload-btn
      title="Avatar"
      :fileChangedCallback="setImage"
      large
      hover
      color="#fff"
      accept="image/*"
      round
    >
```
I'm not using 'a la carte', I'm using version 1.4 of vuetify

**Comment by Machine-Maker** [comment]
getting the same issue. the error goes away when you set the "ripple" prop to false

**Comment by Kritten** [comment]
Setting "ripple" to false did not work for me

**Comment by DoritoBandito** [comment]
I replicated the issue by creating a new project via vue-cli and adding the vue-cli-plugin-vuetify.

Where you have Vue.use(Vuetify), you need to add the Ripple directive as follows:
```
import { Ripple } from 'vuetify/lib/directives'

Vue.use(Vuetify, {
  directives: {
    Ripple
  }
})
```

Please refer to the docs:
https://vuetifyjs.com/en/framework/a-la-carte

**Comment by stevyrino** [comment]
I get this error when setting up the import as above:
Could not find a declaration file for module 'vuetify/lib/directives'.

**Comment by Skriptach** [comment]
I got error too

```bash
 FATAL  Invalid or unexpected token

  @import '../../styles/styles.sass'
  ^

  SyntaxError: Invalid or unexpected token
  at Object.compileFunction (vm.js:403:10)
  at Generator.next (<anonymous>)
  at Object.<anonymous> (node_modules\vuetify\lib\directives\ripple\index.js:1)
  at Generator.next (<anonymous>)
```

**Comment by lxblvs** [comment]
Why is this happening by default?

**Comment by EO2875** [comment]
As @lxblvs points out, I understand that this is not technically a bug. However, ripple should be off by default.
