### ISSUE TITLE
How to upload same file twice?

### ISSUE THREAD

**Issue by alaahong** [DoritoBandito/vuetify-upload-button#23]
Thanks for your efforts on such component.
I just met one issue which I'm not sure whether caused by my incorrect usage.
Here is the tag:

```
                                        <upload-btn
                                          :depressed="true"
                                          :ripple="false"
                                          :color="`theme--light`"
                                          :uniqueId = "true"
                                          :fileChangedCallback="transUploadFileForCust"
                                        ></upload-btn>
```
    "vue": "^2.6.6",
    "vuetify": "^1.5.5",
    "vuetify-upload-button": "^1.2.2",

If I upload same file twice, the second time will no response for "fileChangedCallback", only if I select another file to upload, then the file can be uploaded. 
e.g. file1, file1 will not upload second file1;   file1, file2, file1, all files can upload.
I guess that's caused by no file changed, but that's not friend if user really want to upload twice.

Do you have any idea to avoid such  "no response"?

Thanks in advance.

**Comment by n4ks** [comment]
and if the file has been deleted it is impossible to reload it, only downloading of another file helps, and then the necessary one, something like: 
file1 - upload 
file1 - deleted 
file-1 - upload fail 
file-2 upload 
file-1 upload - ok

**Comment by DoritoBandito** [comment]
@alaahong you could clear the input before uploading the new file like so
`<UploadBtn
        ref="uploadButton"
        @click.native="$refs.uploadButton.clear()"
      />`

**Comment by magvan** [comment]
does not work
Error in v-on handler: "TypeError: _vm.$refs.uploadButton.clear is not a function"

**Comment by DoritoBandito** [comment]
@magvan what version are you using? clear() function was added in release 2.0.0
