### ISSUE TITLE
spaces between icon and text

### ISSUE THREAD

**Issue by andreanta** [DoritoBandito/vuetify-upload-button#32]
Hi, if we set title and icon the icon is too close, if i set with standard vuetify button looks different

`  <upload-btn
                  title="UPLOAD FILE"
                  color="red"
                  class="accent--text"
                >
                  <template slot="icon-left">
                    <v-icon>cloud_upload</v-icon>
                  </template>
                </upload-btn>`

` 

                <v-btn
                  color="primary"
                  class="accent--text"
                  @click="uploadFile()"
                >
                  <v-icon left>cloud_upload</v-icon>UPLOAD FILE
                </v-btn>`

![Cattura_2](https://user-images.githubusercontent.com/18226768/59915604-50ad2e00-941d-11e9-9e78-24ebe95bb341.JPG)

**Comment by DoritoBandito** [comment]
In your code you provided, you have not added left to v-icon, even though you have slot 'icon-left', you still need to put 'left' onto `<v-icon>` like `<v-icon left>`
