### ISSUE TITLE
Documentation & Feature suggestions

### ISSUE THREAD

**Issue by lspohn** [DoritoBandito/vuetify-upload-button#4]
Hey, I'm trying to use your module for our project and it would be great to get a more detailed documentation. E.g. I don't find anything about constructing the callback function.

What would also be great:
- Allow HTML styling of Button text
- Allow setting of icon alignment (left, right)
- Include "depressed" property of v-btn

Thanks a lot so far for your work!

Lucas

**Comment by DoritoBandito** [comment]
Added callback example to docs.
Added 'icon-left' slot so can now have 'icon' (which is right) or 'icon-left' slot. Or both.
Added 'depressed' prop to depress button.
