### ISSUE TITLE
[Vue warn]: Failed to resolve directive: ripple

### ISSUE THREAD

**Issue by mthelm85** [DoritoBandito/vuetify-upload-button#5]
I'm importing the upload button into one of my components and this message prints to the console every time my page loads...any idea as to how to fix it?

**Comment by DoritoBandito** [comment]
I was unable to replicate this issue so I took a look at your repo, you're using a-la-carte. You will need to add the Ripples directive to vuetify/src/plugins/vuetify.js in your project.
