### ISSUE TITLE
Cannot be used multiple times

### ISSUE THREAD

**Issue by vaclavhodek** [DoritoBandito/vuetify-upload-button#7]
Using version 1.1.0 from NPM:

You have id attribute of the input element set to a constant which prevents the component from being used multiple times on the same page. Clicking the upload button will always dispatch the click event to the first component on the page. 

Try to add something like this._uid to the id attribute.

**Comment by DoritoBandito** [comment]
Added uniqueId prop which if true will use `${this._uid}uploadFile` for Id.

**Comment by vaclavhodek** [comment]
Thx man, great work! Thumbs up.
